### ISSUE TITLE
Comments inside a code block are shown as titles

### ISSUE THREAD

**Issue by beshoyabdelmalak** [codejamninja/sphinx-markdown-parser#12]
Comments within a code block would be shown as titles. A workaround would be to indent all the comments in order to make them appear as intended.

[markdown-bug-hash-char.zip](https://github.com/codejamninja/sphinx-markdown-parser/files/3891691/markdown-bug-hash-char.zip)

**Comment by infinity0** [comment]
I think this might be a python-markdown bug. If you enable the 'fenced_code' extension the problem goes away. (Or the 'extra' extension, which implies the 'fenced_code' extension.)

**Comment by infinity0** [comment]
Yeah, it's a python-markdown bug, nothing to do with this extension (or my recent rewrite):

~~~~
>>> import markdown
>>> markdown.markdown("```python\n# comment\n```")
'<p>```python</p>\n<h1>comment</h1>\n<p>```</p>'
~~~~

You can work-around this for now by enabling the extension I mentioned.

**Comment by infinity0** [comment]
@beshoyabdelmalak sorry, actually it's not a python-markdown bug. The point is plain markdown does not support the "```" syntax, that is a github extension that some "flavours" have implemented. You will *have* to enable the fenced_code extension (or "extra") to support what you're trying to do, see https://python-markdown.github.io/extensions/

**Comment by infinity0** [comment]
i.e. this is not a bug, should be closed.

**Comment by clayrisser** [comment]
Cool, thanks for looking into this @infinity0
